# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('column1', models.CharField(max_length=100)),
                ('column2', models.CharField(max_length=100)),
                ('column3', models.CharField(max_length=100)),
                ('column4', models.CharField(max_length=100)),
                ('column5', models.CharField(max_length=100)),
                ('column6', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='grades',
            name='tenant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formupload.Tenant'),
        ),
    ]
