# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 03:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formupload', '0002_auto_20170417_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grades',
            name='tenant_id',
        ),
    ]
