# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formupload', '0003_remove_grades_tenant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formupload.Tenant'),
        ),
    ]
