# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formupload', '0004_grades_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_attribute1', models.CharField(blank=True, max_length=100)),
                ('score_attribute2', models.CharField(blank=True, max_length=100)),
                ('score_attribute3', models.CharField(blank=True, max_length=100)),
                ('score_attribute4', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'TENANT_SCORES',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='grades',
            name='tenant',
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='tenant',
            table='TENANT_DETAILS',
        ),
        migrations.DeleteModel(
            name='Grades',
        ),
        migrations.AddField(
            model_name='scores',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formupload.Tenant'),
        ),
    ]
