# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formupload', '0005_auto_20170424_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='score_attribute1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='score_attribute2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='score_attribute3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='score_attribute4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
