# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formupload', '0006_auto_20170424_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='score_attribute1',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
