# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formupload', '0007_auto_20170424_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='test_case',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scores',
            name='score_attribute1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
